### ISSUE TITLE
Inconsistent import location

### ISSUE THREAD

**Issue by deppy-v2** [zcot/conky-manager2#43]
The import location is inconsistent when compared to the original conky manager. When importing themes they are copied into ~/.conky instead of ~/.config/conky. The themes then break because they usually reference ~/.config/conky in script. To fix either the script has to be manually changed or the themes imported to ~/.config/conky folder to make them work.

Also the default location seems non editable.

**Comment by deppy-v2** [comment]
It seems the old Conky manager was also having the same import folder. Not sure why all the themes I downloaded refer to ~/.config/conky in scripts.

**Comment by zcot** [comment]
You can also add `~/.config/conky` to the manager locations.

I will look into a possibility for this. Yes, a lot of old themes seem to use that location so it would be good to be able to import them there when needed. But also, most of those are pre-1.10 version and even though the later versions of conky do have the automatic conversion when loaded there was 1 or 2 updated versions that had broken that feature so they wouldn't run anyway, it would require a manual conversion to the 1.10+ script format (this way conky will end up not using the automatic broken conversion option). The latest versions of conky now have this feature fixed again, but it is still probably the best setup to have them converted anyway since there are some rare edge cases where the conversion does not completely cover every case anyway.

**Comment by deppy-v2** [comment]
Thanks a ton for your reply. The auto conversion sure will be nice to have for conky newbies like myself.  Meanwhile I think converting the older themes manually seems the best solution

PS: Have closed this ticket from my side, upto you how you want to keep it your radar.
